/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef _SI_DPNS_HW_H
#define _SI_DPNS_HW_H

#include <linux/types.h>

typedef struct sf_dpns DPNS_t;
typedef struct sf_dpns_ops dpns_ops_t;

#define NPU_MIB_ADDR		0x381000
#define NPU_MIB_BYTES_LO	0x38301c
#define NPU_MIB_BYTES_HI	0x383020

enum dpa_cmd_type {
	CMD_TYPE_UNSPEC = 0,
	CMD_TYPE_GET_PORT_SETTINGS,
	CMD_TYPE_SET_PORT_SETTINGS,
	CMD_TYPE_OF_DPA_FLOW_ADD,
	CMD_TYPE_OF_DPA_FLOW_MOD,
	CMD_TYPE_OF_DPA_FLOW_DEL,
	CMD_TYPE_OF_DPA_FLOW_GET_STATS,
	CMD_TYPE_OF_DPA_GROUP_ADD,
	CMD_TYPE_OF_DPA_GROUP_MOD,
	CMD_TYPE_OF_DPA_GROUP_DEL,
	CMD_TYPE_OF_DPA_GROUP_GET_STATS,
	CMD_TYPE_CLEAR_PORT_STATS,
	CMD_TYPE_GET_PORT_STATS,
	CMD_TYPE_MAX,
};

/* OF-DPA table IDs */
enum dpa_table_id {
	DPA_TABLE_ID_VLAN = 0,
	DPA_TABLE_ID_TERMINATION_MAC,
	DPA_TABLE_ID_UNICAST_ROUTING,
	DPA_TABLE_ID_MULTICAST_ROUTING,
	DPA_TABLE_ID_BRIDGING,
	DPA_TABLE_ID_ACL_POLICY,
	DPA_TABLE_ID_MAX,
};
const char* dpa_tbl_name(int tbl);

/* OF-DPA group types */
enum dpa_group_type {
	DPA_GROUP_TYPE_L2_INTERFACE = 0,
	DPA_GROUP_TYPE_L2_REWRITE,
	DPA_GROUP_TYPE_L3_UCAST,
	DPA_GROUP_TYPE_L2_MCAST,
	DPA_GROUP_TYPE_L2_FLOOD,
	DPA_GROUP_TYPE_L3_INTERFACE,
	DPA_GROUP_TYPE_L3_MCAST,
	DPA_GROUP_TYPE_L3_ECMP,
	DPA_GROUP_TYPE_L2_OVERLAY,
	DPA_GROUP_TYPE_MAX,
};
const char *dpa_grp_name(int grp);

/* OF-DPA group L2 overlay types */
enum dpa_overlay_type {
	DPA_OVERLAY_TYPE_FLOOD_UCAST = 0,
	DPA_OVERLAY_TYPE_FLOOD_MCAST,
	DPA_OVERLAY_TYPE_MCAST_UCAST,
	DPA_OVERLAY_TYPE_MCAST_MCAST,
};

enum dpa_ctrl_type {
	DPA_CTRL_LINK_LOCAL_MCAST,
	DPA_CTRL_LOCAL_ARP,
	DPA_CTRL_IPV4_MCAST,
	DPA_CTRL_IPV6_MCAST,
	DPA_CTRL_DFLT_BRIDGING,
	DPA_CTRL_DFLT_OVS,
	DPA_CTRL_MAX,
};

#define DPA_VLAN_ID_BASE	0x0f00
#define DPA_N_VLANS		255
#define DPA_VLAN_BITMAP_LEN	BITS_TO_LONGS(VLAN_N_VID)
#define DPA_UNTAGGED_VID 	(0)

#define DPA_OP_FLAG_REMOVE		BIT(0)
#define DPA_OP_FLAG_NOWAIT		BIT(1)
#define DPA_OP_FLAG_LEARNED		BIT(2)
#define DPA_OP_FLAG_REFRESH		BIT(3)
#define DPA_OP_FLAG_UNRESOLVED	BIT(4)

/* OF-DPA group ID encoding */
#define DPA_GROUP_TYPE_SHIFT 28
#define DPA_GROUP_TYPE_MASK 0xf0000000
#define DPA_GROUP_VLAN_SHIFT 16
#define DPA_GROUP_VLAN_MASK 0x0fff0000
#define DPA_GROUP_PORT_SHIFT 0
#define DPA_GROUP_PORT_MASK 0x0000ffff
#define DPA_GROUP_TUNNEL_ID_SHIFT 12
#define DPA_GROUP_TUNNEL_ID_MASK 0x0ffff000
#define DPA_GROUP_SUBTYPE_SHIFT 10
#define DPA_GROUP_SUBTYPE_MASK 0x00000c00
#define DPA_GROUP_INDEX_SHIFT 0
#define DPA_GROUP_INDEX_MASK 0x0000ffff
#define DPA_GROUP_INDEX_LONG_SHIFT 0
#define DPA_GROUP_INDEX_LONG_MASK 0x0fffffff

#define DPA_GROUP_TYPE_GET(group_id) \
	(((group_id) & DPA_GROUP_TYPE_MASK) >> DPA_GROUP_TYPE_SHIFT)
#define DPA_GROUP_TYPE_SET(type) \
	(((type) << DPA_GROUP_TYPE_SHIFT) & DPA_GROUP_TYPE_MASK)
#define DPA_GROUP_VLAN_GET(group_id) \
	(((group_id) & DPA_GROUP_VLAN_MASK) >> DPA_GROUP_VLAN_SHIFT)
#define DPA_GROUP_VLAN_SET(vlan_id) \
	(((vlan_id) << DPA_GROUP_VLAN_SHIFT) & DPA_GROUP_VLAN_MASK)
#define DPA_GROUP_PORT_GET(group_id) \
	(((group_id) & DPA_GROUP_PORT_MASK) >> DPA_GROUP_PORT_SHIFT)
#define DPA_GROUP_PORT_SET(port) \
	(((port) << DPA_GROUP_PORT_SHIFT) & DPA_GROUP_PORT_MASK)
#define DPA_GROUP_INDEX_GET(group_id) \
	(((group_id) & DPA_GROUP_INDEX_MASK) >> DPA_GROUP_INDEX_SHIFT)
#define DPA_GROUP_INDEX_SET(index) \
	(((index) << DPA_GROUP_INDEX_SHIFT) & DPA_GROUP_INDEX_MASK)
#define DPA_GROUP_INDEX_LONG_GET(group_id) \
	(((group_id) & DPA_GROUP_INDEX_LONG_MASK) >> \
	 DPA_GROUP_INDEX_LONG_SHIFT)
#define DPA_GROUP_INDEX_LONG_SET(index) \
	(((index) << DPA_GROUP_INDEX_LONG_SHIFT) & \
	 DPA_GROUP_INDEX_LONG_MASK)

#define DPA_GROUP_NONE 0
#define DPA_GROUP_L2_INTERFACE(vlan_id, port) \
	(DPA_GROUP_TYPE_SET(DPA_GROUP_TYPE_L2_INTERFACE) |\
	 DPA_GROUP_VLAN_SET(ntohs(vlan_id)) | DPA_GROUP_PORT_SET(port))
#define DPA_GROUP_L2_REWRITE(index) \
	(DPA_GROUP_TYPE_SET(DPA_GROUP_TYPE_L2_REWRITE) |\
	 DPA_GROUP_INDEX_LONG_SET(index))
#define DPA_GROUP_L2_MCAST(vlan_id, index) \
	(DPA_GROUP_TYPE_SET(DPA_GROUP_TYPE_L2_MCAST) |\
	 DPA_GROUP_VLAN_SET(ntohs(vlan_id)) | DPA_GROUP_INDEX_SET(index))
#define DPA_GROUP_L2_FLOOD(vlan_id, index) \
	(DPA_GROUP_TYPE_SET(DPA_GROUP_TYPE_L2_FLOOD) |\
	DPA_GROUP_VLAN_SET(ntohs(vlan_id)) | DPA_GROUP_INDEX_SET(index))
#define DPA_GROUP_L3_UNICAST(index) \
	(DPA_GROUP_TYPE_SET(DPA_GROUP_TYPE_L3_UCAST) |\
	 DPA_GROUP_INDEX_LONG_SET(index))

#endif
