# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the siflower soc network device drivers.
#

sfXgmac-y = sfxgmac.o

obj-$(CONFIG_NET_SIFLOWER_ETH_GMAC) += sfgmac.o
obj-$(CONFIG_NET_SIFLOWER_ETH_XGMAC) += sfXgmac.o
obj-$(CONFIG_NET_SIFLOWER_ETH_XPCS) += sfxpcs.o
obj-$(CONFIG_NET_SIFLOWER_ETH_DMA) += sfxgmac-dma.o
